/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.Criptografar;
import modeloBeans.Usuarios;
import modeloDAO.UsuariosDAO;

/**
 *
 * @author Saulo
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    private UsuariosDAO uDao = new UsuariosDAO();
    private Usuarios u = new Usuarios();
    
    public TelaLogin() {
        initComponents();
        txtUsuario.setText("sauloivo");
            txtPassord.setText("123");
        
        if(uDao.consultar() == null){
            firstUser();
            txtUsuario.setText("admin");
            txtPassord.setText("123");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAcessar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassord = new javax.swing.JPasswordField();
        labelUserFoto = new javax.swing.JLabel();
        labelInv = new javax.swing.JLabel();
        labelImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnAcessar.setText("Acessar");
        btnAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcessar);
        btnAcessar.setBounds(300, 150, 80, 30);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(400, 150, 51, 30);

        jLabel1.setText("Usuário:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 60, 50, 20);

        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 100, 40, 20);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(300, 50, 170, 30);
        getContentPane().add(txtPassord);
        txtPassord.setBounds(300, 100, 170, 30);

        labelUserFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_trasnparency.png"))); // NOI18N
        getContentPane().add(labelUserFoto);
        labelUserFoto.setBounds(80, 30, 130, 170);
        getContentPane().add(labelInv);
        labelInv.setBounds(300, 130, 130, 20);

        labelImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaFundo1.jpg"))); // NOI18N
        getContentPane().add(labelImagemFundo);
        labelImagemFundo.setBounds(0, 0, 500, 240);

        setSize(new java.awt.Dimension(516, 276));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarActionPerformed
        u = uDao.consultaLoginSenha(txtUsuario, txtPassord);
            if(u != null){
                TelaPrincipal tela = new TelaPrincipal(u);
                tela.setVisible(true);
                tela.setResizable(false);
                tela.testeFirstUser();
                dispose();
            }else{
                labelInv.setText("Campos Invalidos");
            }
    }//GEN-LAST:event_btnAcessarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    public void firstUser(){
        if(uDao.consultaLoginSenha("admin", Criptografar.encriptografar("123")) == null){
            Usuarios u = new Usuarios("admin", "Administrador", Criptografar.encriptografar("123"), "Administrador");
            uDao.inserir(u);
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelImagemFundo;
    private javax.swing.JLabel labelInv;
    private javax.swing.JLabel labelUserFoto;
    private javax.swing.JPasswordField txtPassord;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
