/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.Criptografar;
import javax.swing.JOptionPane;
import modeloBeans.Usuarios;
import modeloDAO.AgendaDAO;
import modeloDAO.MedicosDAO;
import modeloDAO.PacientesDAO;
import modeloDAO.UsuariosDAO;

/**
 *
 * @author Saulo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static Usuarios controle_usuario;
    private static FormMedico cadMedico = null;
    private static FormUsuario cadUsuario = null;
    private static FormPaciente cadPaciente = null;
    private static FormAgenda cadAgenda = null;
    private static FormRelatorio relatorio = null;
    private static MedicosDAO mDao = new MedicosDAO();
    private static AgendaDAO aDao = new AgendaDAO();
    private static UsuariosDAO uDao = new UsuariosDAO();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(Usuarios controle_usuario) {
        initComponents();
        this.controle_usuario = controle_usuario;
        labelUsuarios.setText(controle_usuario.getNome());
    }

    private TelaPrincipal() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrameBemVindo = new javax.swing.JInternalFrame();
        painelBemVindos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCadMedicos = new javax.swing.JButton();
        btnCadPacientes = new javax.swing.JButton();
        labelAgenda = new javax.swing.JLabel();
        btnAgenda = new javax.swing.JButton();
        labelFundoMedico = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnFecharBemVindo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelUsuarios = new javax.swing.JLabel();
        labelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCadastro = new javax.swing.JMenu();
        menuItemCadMed = new javax.swing.JMenuItem();
        menuItemCadPaciente = new javax.swing.JMenuItem();
        menuItemCadUsuario = new javax.swing.JMenuItem();
        mRelatorios = new javax.swing.JMenu();
        mFerramentas = new javax.swing.JMenu();
        menuItemFerramBemVindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        internalFrameBemVindo.setTitle("Bem-Vindos");
        internalFrameBemVindo.setVisible(true);
        internalFrameBemVindo.getContentPane().setLayout(null);

        painelBemVindos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelBemVindos.setLayout(null);

        jLabel2.setText("Cadastros ");
        painelBemVindos.add(jLabel2);
        jLabel2.setBounds(10, 10, 70, 14);

        btnCadMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/medico_transparency.png"))); // NOI18N
        btnCadMedicos.setToolTipText("Medicos");
        btnCadMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadMedicosActionPerformed(evt);
            }
        });
        painelBemVindos.add(btnCadMedicos);
        btnCadMedicos.setBounds(10, 30, 80, 90);

        btnCadPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/paciente.png"))); // NOI18N
        btnCadPacientes.setToolTipText("Pacientes");
        btnCadPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPacientesActionPerformed(evt);
            }
        });
        painelBemVindos.add(btnCadPacientes);
        btnCadPacientes.setBounds(100, 30, 80, 90);

        labelAgenda.setText("Agenda");
        painelBemVindos.add(labelAgenda);
        labelAgenda.setBounds(20, 130, 60, 14);

        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agenda.png"))); // NOI18N
        btnAgenda.setToolTipText("Horarios Consultas");
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });
        painelBemVindos.add(btnAgenda);
        btnAgenda.setBounds(10, 150, 80, 70);

        labelFundoMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaFundoBemVindos.jpg"))); // NOI18N
        painelBemVindos.add(labelFundoMedico);
        labelFundoMedico.setBounds(0, 1, 850, 230);

        internalFrameBemVindo.getContentPane().add(painelBemVindos);
        painelBemVindos.setBounds(10, 40, 840, 230);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de:");
        internalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 240, 40);

        btnFecharBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar.png"))); // NOI18N
        btnFecharBemVindo.setToolTipText("Fechar Bem-Vindo");
        btnFecharBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharBemVindoActionPerformed(evt);
            }
        });
        internalFrameBemVindo.getContentPane().add(btnFecharBemVindo);
        btnFecharBemVindo.setBounds(830, 0, 30, 30);

        getContentPane().add(internalFrameBemVindo);
        internalFrameBemVindo.setBounds(10, 150, 880, 310);

        jLabel3.setText("Usuario: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 460, 50, 20);
        getContentPane().add(labelUsuarios);
        labelUsuarios.setBounds(70, 460, 220, 20);

        labelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaFundoPrincipal.jpg"))); // NOI18N
        getContentPane().add(labelFundoPrincipal);
        labelFundoPrincipal.setBounds(0, 0, 900, 480);

        mCadastro.setText("Cadastro");

        menuItemCadMed.setText("Médicos");
        menuItemCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadMedActionPerformed(evt);
            }
        });
        mCadastro.add(menuItemCadMed);

        menuItemCadPaciente.setText("Pacientes");
        menuItemCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadPacienteActionPerformed(evt);
            }
        });
        mCadastro.add(menuItemCadPaciente);

        menuItemCadUsuario.setText("Usuarios");
        menuItemCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadUsuarioActionPerformed(evt);
            }
        });
        mCadastro.add(menuItemCadUsuario);

        jMenuBar1.add(mCadastro);

        mRelatorios.setText("Relatorios");
        mRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mRelatoriosMouseClicked(evt);
            }
        });
        jMenuBar1.add(mRelatorios);

        mFerramentas.setText("Ferramentas");

        menuItemFerramBemVindo.setText("Tela Bem-Vindo");
        menuItemFerramBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFerramBemVindoActionPerformed(evt);
            }
        });
        mFerramentas.add(menuItemFerramBemVindo);

        jMenuBar1.add(mFerramentas);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(916, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadMedActionPerformed
        if(controle_usuario.getTipo().equals("Administrador")){
            if(cadMedico == null){
                cadMedico = new FormMedico();
                cadMedico.setVisible(true);
                cadMedico.setResizable(false);
            } else{
                cadMedico.setVisible(true);
                cadMedico.popularTabela(mDao.consultar());
            }        
        } else{
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar essa função.\nContante o administrador do sistema.");
        }
    }//GEN-LAST:event_menuItemCadMedActionPerformed

    private void btnFecharBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharBemVindoActionPerformed
        internalFrameBemVindo.dispose();
    }//GEN-LAST:event_btnFecharBemVindoActionPerformed

    private void menuItemFerramBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFerramBemVindoActionPerformed
        internalFrameBemVindo.setVisible(true);
    }//GEN-LAST:event_menuItemFerramBemVindoActionPerformed

    private void btnCadMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadMedicosActionPerformed
        if (controle_usuario.getTipo().equals("Administrador")) {
            if(cadMedico == null){
                cadMedico = new FormMedico();
                cadMedico.setVisible(true);
                cadMedico.setResizable(false);
            } else{
                cadMedico.setVisible(true);
                cadMedico.popularTabela(mDao.consultar());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar essa função.\nContate o administrador do sistema.");
        }
    }//GEN-LAST:event_btnCadMedicosActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void menuItemCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadUsuarioActionPerformed
        if(controle_usuario.getTipo().equals("Administrador")){
            if(cadUsuario == null){
                cadUsuario = new FormUsuario();
                cadUsuario.setVisible(true);
                cadUsuario.setResizable(false);
            } else{
                cadUsuario.setVisible(true);
                cadUsuario.populaTabela();
            }         
        } else{
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar essa função.\nContante o administrador do sistema.");
        }
    }//GEN-LAST:event_menuItemCadUsuarioActionPerformed

    private void btnCadPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacientesActionPerformed
        if(controle_usuario.getTipo().equals("Administrador")){
            if(cadPaciente == null){
                cadPaciente = new FormPaciente();
                cadPaciente.setVisible(true);
                cadPaciente.setResizable(false);
            } else{
                cadPaciente.setVisible(true);
                cadPaciente.populaTabela();
            }
        } else{
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar essa função.\nContate o administrador do sistema.");
        } 
    }//GEN-LAST:event_btnCadPacientesActionPerformed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
        if(cadAgenda == null){
            cadAgenda = new FormAgenda();
            cadAgenda.setVisible(true);
            cadAgenda.setResizable(false);
        }else{
            cadAgenda.setVisible(true);
            cadAgenda.populaTabela();
            cadAgenda.populaComboBox();
        }
        
    }//GEN-LAST:event_btnAgendaActionPerformed

    private void mRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mRelatoriosMouseClicked
        if(relatorio == null){
            relatorio = new FormRelatorio();
            relatorio.setVisible(true);
            relatorio.setResizable(false);
        }else{
            relatorio.setVisible(true);
            relatorio.populaMedicos();
            relatorio.populaTabela(aDao.listar());
        }
    }//GEN-LAST:event_mRelatoriosMouseClicked

    private void menuItemCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadPacienteActionPerformed
        if(controle_usuario.getTipo().equals("Administrador")){
            if(cadPaciente == null){
                cadPaciente = new FormPaciente();
                cadPaciente.setVisible(true);
                cadPaciente.setResizable(false);
            } else{
                cadPaciente.setVisible(true);
                cadPaciente.populaTabela();
            }
        } else{
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar essa função.\nContate o administrador do sistema.");
        }
    }//GEN-LAST:event_menuItemCadPacienteActionPerformed
    
    public void testeFirstUser(){
        Usuarios u = uDao.consultaLoginSenha("admin", Criptografar.encriptografar("123"));
        if(u != null){
            if(cadUsuario == null){
                cadUsuario = new FormUsuario();
                cadUsuario.setVisible(true);
                cadUsuario.setResizable(false);
            } else{
                cadUsuario.setVisible(true);
                cadUsuario.populaTabela();
            }   
            JOptionPane.showMessageDialog(null, "Por favor insira um novo usuario.\nO Atual será apagado", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnCadMedicos;
    private javax.swing.JButton btnCadPacientes;
    private javax.swing.JButton btnFecharBemVindo;
    private javax.swing.JInternalFrame internalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JLabel labelAgenda;
    private javax.swing.JLabel labelFundoMedico;
    private javax.swing.JLabel labelFundoPrincipal;
    private javax.swing.JLabel labelUsuarios;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenu mFerramentas;
    private javax.swing.JMenu mRelatorios;
    private javax.swing.JMenuItem menuItemCadMed;
    private javax.swing.JMenuItem menuItemCadPaciente;
    private javax.swing.JMenuItem menuItemCadUsuario;
    private javax.swing.JMenuItem menuItemFerramBemVindo;
    private javax.swing.JPanel painelBemVindos;
    // End of variables declaration//GEN-END:variables

    
}
